name: ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '30 21 * * *'
permissions: {}
defaults:
  run:
    shell: bash -euo pipefail {0}
jobs:
  build-linux:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
        with:
          path: |
            ~/.cache/org.swift.swiftpm
            ~/.swiftpm
            .build
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('Package.resolved') }}
          restore-keys: ${{ runner.os }}-swiftpm-
      - run: ./scripts/ci-install-swift.sh
      - run: swift --version
      - run: swift build -c release --triple aarch64-none-none-elf --toolset toolset.json --explicit-target-dependency-import-check error
  build-macos:
    runs-on: macos-26
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - run: ./scripts/ci-install-swift.sh
      - run: swift --version
      - run: swift build -c release --triple aarch64-none-none-elf --toolset toolset.json --explicit-target-dependency-import-check error
  lint:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - run: ./scripts/ci-install-swift.sh
      - run: swift --version
      - run: swift format lint -rsp .
  yamllint:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - run: yamllint --version
      - run: yamllint --strict --config-file .yamllint.yml .
  shellcheck:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - run: shellcheck -V
      - run: git ls-files -z '*.sh' | xargs -0 --no-run-if-empty shellcheck -x
  results:
    if: ${{ always() }}
    runs-on: ubuntu-24.04-arm
    needs: [build-linux, build-macos, lint, yamllint, shellcheck]
    steps:
      - run: exit 1
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
